stadiumIdList:
  Badminton Court 1: '5'
  Badminton Court 2: '6'
  Badminton Court 3: '7'
  Badminton Court 4: '8'
  Badminton Court 5: '13'
  Badminton Court 6: '14'

periodIdList:
  15:x0 - 16:00: '21'
#  15:00 - 16:00: '22'
  16:00 - 17:00: '2'
  17:00 - 18:00: '3'
  18:00 - 19:00: '4'
  19:00 - 20:00: '5'
  20:00 - 21:00: '6'

basicHeaders:
  Host: tyb.qingyou.ren
  User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; SM-G977N Build/LMY48Z; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36 MMWEBID/4347 MicroMessenger/8.0.22.2140(0x280016F7) WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32 MiniProgramEnv/android
  Charset: utf-8
  Accept-Encoding: gzip, deflate

host: https://tyb.qingyou.ren
# some token that need to be updated every day.